### ISSUE TITLE
fromFile not exist cause queue NPE

### ISSUE THREAD

**Issue by WesleyOne** [apache/rocketmq-streams#127]
plz close this issue if same as #90 

org.apache.rocketmq.streams.examples.source.FileSourceExample

if fromFile is not exist, will throwing NPE as below.

![截屏2022-01-30 13 02 00](https://user-images.githubusercontent.com/24919538/151687389-83611faa-4a67-4dda-8491-93e53f044464.png)

```
java.lang.NullPointerException
	at org.apache.rocketmq.streams.common.channel.impl.file.FileSource.startSource(FileSource.java:90)
	at org.apache.rocketmq.streams.common.channel.source.AbstractSource.start(AbstractSource.java:114)
	at org.apache.rocketmq.streams.common.topology.ChainPipeline.startChannel(ChainPipeline.java:150)
	at org.apache.rocketmq.streams.client.transform.DataStream$7.run(DataStream.java:714)
	at java.lang.Thread.run(Thread.java:748)
```

how about fast-fail with throwing FileNotFoundException

**Comment by Kvicii** [comment]
@dongeforever hi there,
I think this kind of work to initialize capacity, if necessary, should be added with mandatory verification, but if the performance gap is not big, capacity initialization can be omitted

**Comment by dongeforever** [comment]
@Kvicii Yeah. it is just be used for initialization, the capacity arg could be omitted.

**Comment by Kvicii** [comment]
@dongeforever 
Let me re-judg the size so that no NPE is thrown.

**Comment by dongeforever** [comment]
@WesleyOne LGTM.
It's better to throw an exception when the initialization encounters an unexpected error. 
It's not a good idea to treat the 'file not found error' as an empty stream.
you may submit a pr to fix it.
