### ISSUE TITLE
RemoteCheckpointExample error.

### ISSUE THREAD

**Issue by ni-ze** [apache/rocketmq-streams#161]
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '/* * Licensed to the Apache Software Foundation (ASF) under one or more * contri' at line 1
  at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
  at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
  at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:762)

**Comment by ni-ze** [comment]
https://github.com/apache/rocketmq-streams/pull/160
