### ISSUE TITLE
The `WordCount` example cannot run successfully

### ISSUE THREAD

**Issue by elenacliu** [apache/rocketmq-streams#305]
I'm sure that my code is in sync with the develop branch, because I just click `sync with upstream` on my forked repo, then pull to my local machine.

I found that when I ran `wordCount` example, it would run into errors like this:

```bash
> mvn exec:java -Dexec.mainClass="org.apache.rocketmq.streams.examples.WordCount" -pl example
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.apache.rocketmq:rocketmq-streams-example:jar:1.1.2-SNAPSHOT
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ------------< org.apache.rocketmq:rocketmq-streams-example >------------
[INFO] Building rocketmq-streams-example 1.1.2-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec:3.1.0:java (default-cli) @ rocketmq-streams-example ---
2023-07-08 09:12:10.234 [ROCKETMQ_STREAMS_wordCount_0] INFO  org.apache.rocketmq.streams.core.util.RocketMQUtil - topic[wordCount-ROCKETMQ-COUNT-00004-shuffleTopic] already exist.
2023-07-08 09:12:10.254 [ROCKETMQ_STREAMS_wordCount_0] INFO  o.a.rocketmq.streams.core.running.WorkerThread - worker thread=[ROCKETMQ_STREAMS_wordCount_0], start task success, jobId:wordCount

2023-07-08 09:14:05.090 [ROCKETMQ_STREAMS_wordCount_0] ERROR o.a.rocketmq.streams.core.running.WorkerThread - process error.
org.apache.rocketmq.client.exception.MQClientException: The broker[bogon] not exist
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:952)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendSelectImpl(DefaultMQProducerImpl.java:1209)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1175)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1170)
        at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:534)
        at org.apache.rocketmq.streams.core.function.supplier.SinkSupplier$SinkProcessor.process(SinkSupplier.java:102)
        at org.apache.rocketmq.streams.core.running.StreamContextImpl.forward(StreamContextImpl.java:173)
        at org.apache.rocketmq.streams.core.function.supplier.KeySelectSupplier$MapperProcessor.process(KeySelectSupplier.java:49)
        at org.apache.rocketmq.streams.core.running.StreamContextImpl.forward(StreamContextImpl.java:173)
        at org.apache.rocketmq.streams.core.function.supplier.MultiValueChangeSupplier$MultiValueMapperProcessor.process(MultiValueChangeSupplier.java:64)
        at org.apache.rocketmq.streams.core.running.StreamContextImpl.forward(StreamContextImpl.java:173)
        at org.apache.rocketmq.streams.core.running.WorkerThread$PlanetaryEngine.runInLoop(WorkerThread.java:209)
        at org.apache.rocketmq.streams.core.running.WorkerThread.run(WorkerThread.java:104)
2023-07-08 09:14:05.090 [ROCKETMQ_STREAMS_wordCount_0] ERROR o.a.rocketmq.streams.core.running.WorkerThread - ignore error, jobId=[wordCount], skip this data.
org.apache.rocketmq.streams.core.exception.DataProcessThrowable: org.apache.rocketmq.client.exception.MQClientException: The broker[bogon] not exist
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
        at org.apache.rocketmq.streams.core.running.WorkerThread$PlanetaryEngine.runInLoop(WorkerThread.java:212)
        at org.apache.rocketmq.streams.core.running.WorkerThread.run(WorkerThread.java:104)
Caused by: org.apache.rocketmq.client.exception.MQClientException: The broker[bogon] not exist
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:952)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendSelectImpl(DefaultMQProducerImpl.java:1209)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1175)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1170)
        at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:534)
        at org.apache.rocketmq.streams.core.function.supplier.SinkSupplier$SinkProcessor.process(SinkSupplier.java:102)
        at org.apache.rocketmq.streams.core.running.StreamContextImpl.forward(StreamContextImpl.java:173)
        at org.apache.rocketmq.streams.core.function.supplier.KeySelectSupplier$MapperProcessor.process(KeySelectSupplier.java:49)
        at org.apache.rocketmq.streams.core.running.StreamContextImpl.forward(StreamContextImpl.java:173)
        at org.apache.rocketmq.streams.core.function.supplier.MultiValueChangeSupplier$MultiValueMapperProcessor.process(MultiValueChangeSupplier.java:64)
        at org.apache.rocketmq.streams.core.running.StreamContextImpl.forward(StreamContextImpl.java:173)
        at org.apache.rocketmq.streams.core.running.WorkerThread$PlanetaryEngine.runInLoop(WorkerThread.java:209)
        ... 1 common frames omitted

```

It says the broker doesn't exist, but the namesrv and the broker are both running normally and I can send message to topic `sourceTopic`.

**Comment by ni-ze** [comment]
How can I reproduce it? It is works right on my laptop.

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `type/bug` | Status: **Confirmed**

WordCount example failing to run is a valid bug. Example code should work out-of-the-box to help users get started.

**Root Cause:** Likely a dependency version mismatch, API change, or missing configuration in the example.
**Impact:** Poor developer experience — new users cannot run the introductory example.
**Severity:** Medium — affects onboarding experience.

**Suggested fix:** Verify the example against the current release; update dependencies and API calls as needed.

---
*Automated evaluation by github-manager*
